---
# Add the yarn repo
- name: Add repository
  yum_repository:
    name: yarnrepo
    description: Repo for Yarn, the dependency manager used in the webui.
    baseurl: https://dl.yarnpkg.com/rpm/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://dl.yarnpkg.com/rpm/pubkey.gpg

# Install needed packages
- name: Install dev packages
  dnf:
      name:
      - git
      - docker
      - docker-compose
      - mysql
      - mysql-server
      - httpie
      - python2-pip
      - python3-pip
      - python3-virtualenv
      - python2-virtualenv
      - python3-virtualenvwrapper
      - python2-virtualenvwrapper
      - yarn
      state: present

- name: pip install django-storage-swift
  pip:
      name: django-storage-swift
      executable: pip3

- name: pip install docker
  pip:
      name: docker
      executable: pip3

- name: Install the .bashrc
  copy:
      src: .bashrc
      dest: /home/vagrant/.bashrc
      mode: 0644
      owner: vagrant
      group: vagrant

- name: Install the .vimrc
  copy:
      src: .vimrc
      dest: /home/vagrant/.vimrc
      mode: 0644
      owner: vagrant
      group: vagrant

- name: Install the motd
  copy:
      src: motd
      dest: /etc/motd
      mode: 0644

- name: Create directory for python env
  file: 
      path: /home/vagrant/Python_Envs 
      state: directory
      mode: 0755

- name: Create directory for repos
  file: 
      path: /home/vagrant/Repositories 
      state: directory
      mode: 0755

- name: Create directory for ChRIS_store
  file: 
      path: /home/vagrant/Repositories/ChRIS_store
      state: directory
      mode: 0755

- name: Create directory for ChRIS_store_ui
  file: 
      path: /home/vagrant/Repositories/ChRIS_store_ui
      state: directory
      mode: 0755

- name: Clone ChRIS Store repo
  git:
    repo: 'https://github.com/FNNDSC/ChRIS_store.git'
    dest: /home/vagrant/Repositories/ChRIS_store
    update: yes

- name: Clone ChRIS Store UI repo
  git:
    repo: 'https://github.com/FNNDSC/ChRIS_store_ui.git'
    dest: /home/vagrant/Repositories/ChRIS_store_ui
    update: yes

- name: Install python virtual environment
  pip:
    requirements: /home/vagrant/Repositories/ChRIS_store/requirements/local.txt
    virtualenv: /home/vagrant/Python_Envs

- name: Make python venv using command module
  command: mkvirtualenv --python=python3 chris_store_env
  args:
    chdir: /home/vagrant/Python_Envs

- name: Source .bashrc
  command: source /home/vagrant/.bashrc

- name:  Install dependencies for UI via yarn
  command: yarn install
  args: 
    chdir: /home/vagrant/Repositories/ChRIS_store_ui

